### ISSUE TITLE
Add filtering to protein search

### ISSUE THREAD

**Issue by cooperbailey4** [xnought/venome#136]
Add a filtering system that takes into account different data we can recognize from the database, ex. 

- What Organism, 
- Length of protein, 
- Mass of protein 
- etc.

**Comment by cooperbailey4** [comment]
## Subtasks

- [ ] Filter by Organism
- [ ] Filter by Length of protein
- [ ] Filter by Mass of protein
- [ ] Filters that I haven't mentioned or forgotten to include (will add note of what filters I added later)
