### ISSUE TITLE
Add sorting to protein search

### ISSUE THREAD

**Issue by cooperbailey4** [xnought/venome#137]
Add a way to sort proteins ex. alphabetically, numerically(length-wise), numerically(mass-wise), ascending and descending. Other possible ideas for this may come about but these will be the ones to focus on for this issue.

**Comment by cooperbailey4** [comment]
## Subtasks

- [ ] Sort alphabetically
- [ ] Sort numerically(length-wise)
- [ ] Sort numerically(mass-wise)
- [ ] Add ascending and descending options for sorting
