### ISSUE TITLE
Visualization Setup

### ISSUE THREAD

**Issue by xnought** [xnought/venome#44]
Should take around a day to do basic background research before starting the actual implementation.

## Tasks
- [x] Figure out what is contained in the PDB files
- [x] Download [Molestar](https://github.com/molstar) in the frontend
- [x] Store one PDB file in the frontend for testing and development
