### ISSUE TITLE
Create Visualization Component

### ISSUE THREAD

**Issue by xnought** [xnought/venome#45]
Should take two days to finish up showing a basic visualization if molestar works out. However note that this might take longer based on how difficult it is to use.

## Tasks
- [x] Use Molestar to display the PDB file in three dimensions (est. 1 day)
- [x] Include amino acid sequence at the top (est. 1/2 day)
- [ ] Allow the Svelte component to take PDB file buffer as input (est. 1/2 day)
