### ISSUE TITLE
[User Story] Protein Visualization

### ISSUE THREAD

**Issue by xnought** [xnought/venome#47]
## User story statement
As a venom researcher, I want to visualize a single protein fold structure in three dimensions to gain insight into the structure so that I can discover its function for my venom related research and future publications. 

## Background
- **Why do we want it?** Proteins do virtually everything in organisms and their shape determines how they function.  However, PDB files (plain text) on their own don’t allow people to see the shapes of the proteins. We need a way to transform the PDB file into a three-dimensional shape so we can infer the function.

- **Who is this for?** Biology/Biochem/Biophysics/Genetics Researchers who have AlphaFold protein fold predictions or x-ray crystallography measurements of proteins. They are interested in determining how proteins function and interact based on their shape.

- **Do we have data to support it?** From speaking with our clients, they currently drag and drop PDB files into a desktop application called [ChimeraX](https://www.rbvi.ucsf.edu/chimerax/). They use color encodings and three-dimensional representations of the proteins to figure out the probable function of the protein. The biggest protein database also uses three-dimensional visualizations as a key part of the entries ([Protein Data Bank](https://www.rcsb.org/3d-view/8PBX/1)). 

- **Existing Visualization Libraries.** The visualization of the three-dimensional structure itself looks very similar across many different protein databases. For example, [UniProt](https://www.uniprot.org/uniprotkb/P06213/feature-viewer), [Protein Data Bank](https://www.rcsb.org/3d-view/8PBX/1), and [AlphaFold Database](https://alphafold.ebi.ac.uk/entry/H2NHM8) all use the same visualization software for the structure. They all use the [Mol*](https://molstar.org/) visualization package with nice open-source implementations and APIs. Additionally our client pointed out the [AlphaFold Database](https://alphafold.ebi.ac.uk/entry/H2NHM8) visualization structure as something they would like to have, so using [Mol*](https://molstar.org/) will be absolutely necessary.

## Solution/Requirements
- Both the amino acids and the three-dimensional structure need to be visible to infer function.
- There should be enough help that someone who hasn’t used the software before can interact with the visualization.
- PDB file and visualizations should load in less than 3 seconds.
The visualization should be usable as a Svelte Component and take in PDB data as a prop.

## Design Resources
- Figma for initial wireframes
- Location of the 3D visualization compared to the wiki entry ([on Figma](https://www.figma.com/file/G1pbQsYy4lCTVCvMEnGydX/Unknown-Venome-Project?type=design&node-id=16%3A8&mode=design&t=jnnR8krhSJx8BNtC-1))

## Dependencies
- To fully integrate the visualization, first we need to have proteins stored in the database and request that data to the frontend. For now we can save one PDB file in the frontend for the development of this user story.
- Also dependent on understanding how the PDB files are structured.

## Tasks
The tasks to complete this user story are below. Within the tasks are subtasks to complete the task. In parentheses are estimates for the number of days it would take to accomplish the task.

In total, I estimate all the tasks can be completed in three days at a minimum, and more likely double that to six days at a maximum.
- [x] https://github.com/xnought/venome/issues/44 (est. 1 day) 
  - [x] Figure out what is contained in the PDB files
  - [x] Download [Molestar](https://github.com/molstar) in the frontend
  - [x] Store one PDB file in the frontend for testing and development
- [x] https://github.com/xnought/venome/issues/45 (est. 2 days) 
  - [x] Use Molestar to display the PDB file in three dimensions (est. 1 day)
  - [x] Include amino acid sequence at the top (est. 1/2 day)
  - [x] Allow the Svelte component to take PDB file buffer as input (est. 1/2 day)
- [x] https://github.com/xnought/venome/issues/46 (est. 1 day) (once dependency is finished) 
- [x] Check in with client to see which interactions they like and what more information they want to visualize (during a meeting).

## Open Questions
- How difficult will it be to use the Molestar protein visualization library? 
- Can we pass in a file buffer into Molestar, or do we have to provide a link? (important for how we set up the backend endpoint).
- How can we evaluate whether the visualization is useful for discovering function?

## Acceptance Criteria
- [x] Can visualize any PDB file, especially those from AlphaFold in three dimensions.
- [x] The visualization component is inserted into the wiki entry itself for a certain protein on the top left.
- [x] We can request a PDB from our venom database and display it in the visualization in three dimensions.

## Definition of Done
- [x] Acceptance criteria are validated
- [x] Changes are merged after a code review
- [x] Unit tests pass
- [x] Documentation is updated
- [x] Note and resolve merge conflicts with other features
